/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author dardo
 */
public class Consulta extends javax.swing.JFrame {

    /**
     * Creates new form Consulta
     */
    public Consulta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        fondoCerrar = new javax.swing.JPanel();
        textoCerrar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        buscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPersonas = new javax.swing.JTable();
        fondoDetalles = new javax.swing.JPanel();
        textoDetalles = new javax.swing.JLabel();
        fondoEditar = new javax.swing.JPanel();
        textoEditar = new javax.swing.JLabel();
        fondoEliminar = new javax.swing.JPanel();
        textoEliminar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(700, 580));

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(51, 153, 255));

        fondoCerrar.setBackground(new java.awt.Color(51, 153, 255));

        textoCerrar.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        textoCerrar.setForeground(new java.awt.Color(255, 255, 255));
        textoCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoCerrar.setText("X");

        javax.swing.GroupLayout fondoCerrarLayout = new javax.swing.GroupLayout(fondoCerrar);
        fondoCerrar.setLayout(fondoCerrarLayout);
        fondoCerrarLayout.setHorizontalGroup(
            fondoCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textoCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        fondoCerrarLayout.setVerticalGroup(
            fondoCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoCerrarLayout.createSequentialGroup()
                .addComponent(textoCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(0, 940, Short.MAX_VALUE)
                .addComponent(fondoCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 40));

        jLabel3.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Buscar:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 40));

        buscar.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jPanel1.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 780, 40));

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CONSULTA DE PERSONAS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 360, 30));

        tablaPersonas.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        tablaPersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Apellidos", "Estado", "Municipio", "Discapacidad", "Habilidades"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaPersonas);
        if (tablaPersonas.getColumnModel().getColumnCount() > 0) {
            tablaPersonas.getColumnModel().getColumn(0).setMinWidth(30);
            tablaPersonas.getColumnModel().getColumn(0).setMaxWidth(30);
            tablaPersonas.getColumnModel().getColumn(6).setPreferredWidth(150);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 940, 410));

        fondoDetalles.setBackground(new java.awt.Color(255, 255, 255));

        textoDetalles.setBackground(new java.awt.Color(255, 255, 255));
        textoDetalles.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
        textoDetalles.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoDetalles.setText("Detalles");
        textoDetalles.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout fondoDetallesLayout = new javax.swing.GroupLayout(fondoDetalles);
        fondoDetalles.setLayout(fondoDetallesLayout);
        fondoDetallesLayout.setHorizontalGroup(
            fondoDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textoDetalles, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        fondoDetallesLayout.setVerticalGroup(
            fondoDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textoDetalles, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jPanel1.add(fondoDetalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 600, 170, 70));

        fondoEditar.setBackground(new java.awt.Color(255, 255, 255));

        textoEditar.setBackground(new java.awt.Color(255, 255, 255));
        textoEditar.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
        textoEditar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoEditar.setText("Editar");
        textoEditar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout fondoEditarLayout = new javax.swing.GroupLayout(fondoEditar);
        fondoEditar.setLayout(fondoEditarLayout);
        fondoEditarLayout.setHorizontalGroup(
            fondoEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textoEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        fondoEditarLayout.setVerticalGroup(
            fondoEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textoEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jPanel1.add(fondoEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 600, -1, -1));

        fondoEliminar.setBackground(new java.awt.Color(255, 255, 255));

        textoEliminar.setBackground(new java.awt.Color(255, 255, 255));
        textoEliminar.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
        textoEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoEliminar.setText("Eliminar");
        textoEliminar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout fondoEliminarLayout = new javax.swing.GroupLayout(fondoEliminar);
        fondoEliminar.setLayout(fondoEliminarLayout);
        fondoEliminarLayout.setHorizontalGroup(
            fondoEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textoEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        fondoEliminarLayout.setVerticalGroup(
            fondoEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textoEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jPanel1.add(fondoEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 600, 170, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField buscar;
    public javax.swing.JPanel fondoCerrar;
    public javax.swing.JPanel fondoDetalles;
    public javax.swing.JPanel fondoEditar;
    public javax.swing.JPanel fondoEliminar;
    public javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tablaPersonas;
    public javax.swing.JLabel textoCerrar;
    public javax.swing.JLabel textoDetalles;
    public javax.swing.JLabel textoEditar;
    public javax.swing.JLabel textoEliminar;
    // End of variables declaration//GEN-END:variables
}
